baseurl = "/"
languageCode = "en-us"
paginate = 5
[languages.en]
copyright = ""
keywords = ""
languageName = "English"
menuMore = "Show more"
missingBackButtonLabel = "Back to home page"
missingContentMessage = "Page not found..."
newerPosts = "Newer posts"
olderPosts = "Older posts"
owner = ""
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "A simple, retro theme for Hugo"
title = "Terminal"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "Terminal"
[params]
autoCover = true
centerTheme = false
contentTypeName = "posts"
fullWidthTheme = false
showLanguageSelector = false
showLastUpdated = false
showMenuItems = 3
themeColor = "red"
[params.twitter]
creator = ""
site = ""
